### ISSUE TITLE
PostCSS error

### ISSUE THREAD

**Issue by aadgrant** [KimPaow/sanity-plugin-dark-mode#1]
After upgrading Sanity, I'm getting the following error. When I remove `sanity-plugin-dark-mode`, the error goes away.

`Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but postcss-custom-properties uses 7.0.35. Perhaps this is the source of the error below.

Failed to read CSS custom properties: Syntax Error at line: 1, column 34`

**Comment by KimPaow** [comment]
What version did you update from and to?

This seems odd, have you tried if any other themes work?

**Comment by aadgrant** [comment]
Agreed, it seems baffling. The dark-theme-blue had the same issue after I
added it. Tried clearing out node_modules/yarn.lock without luck.

I was upgrading from 2.0.9 to latest version (2.10.2) so quite an upgrade.

Also tried one by one disabling and reenabling my other plugins. Yours was
the last I came to. Must be something changed in the postcss configs that's
affecting the variables used.
