### ISSUE TITLE
Content blocks don't change to white text

### ISSUE THREAD

**Issue by aidanm1999** [KimPaow/sanity-plugin-dark-mode#2]
# Actual
The text within the block type does not change to white (see text in the Content field):

<div style="display:flex">
<img width="400" alt="Screenshot 2022-01-13 at 4 52 38 pm" src="https://user-images.githubusercontent.com/36016925/149373983-6e85904d-0927-4f5c-abad-7257ce53ec89.png">
<img width="400" alt="Screenshot 2022-01-13 at 4 52 56 pm" src="https://user-images.githubusercontent.com/36016925/149374011-46602128-79ab-4f5a-baef-a6fbb80f6f1a.png">
</div>

<br/>

Below is the schema snippet for the block: 

``` javascript
{
    title: "Content",
    name: "text",
    type: "array",
    of: [{ type: "block" }, { type: "image" }],
},
```

# Expected
Whilst editing, it would be good if the text within the content section is white instead of black/dark blue. 

Thanks!

**Comment by sachinsancheti1** [comment]
Got the same issue. 
Probably there has been some change in the variables? Below is the debug code from the console

```
could not convert color `--brand-faded: color(#145eda blend(rgba(53, 61, 79, 0.2) 60%))`
could not convert color `--input-bg-disabled: color(color(#121723 lightness(+ 30%)) blend(rgba(53, 61, 79, 0.2) 75%))`
```

**Comment by drac-dot-gay** [comment]
Vouch, I'm having the same issue and console messages.

**Comment by KimPaow** [comment]
Thanks for the heads up! Will look into this asap

**Comment by KimPaow** [comment]
I took a look into this and from what I can see it seems like they added `mix-blend-mode: multiply;` to the editors text container. This is a problem in dark mode since multiply will, well, make every color darker the lighter it is. E.g. white becomes black. 

I published a quick fix where i force all cards to have a normal blend mode instead. Let me know if this fix solved your problems 👍

**Comment by sachinsancheti1** [comment]
Looks good, I just tried it. I can happily ignore the console log as long as the studio works.

**Comment by aidanm1999** [comment]
Works like a dream thanks for the help!
